// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-gradient-to-r from-blue-800 to-indigo-800 text-white\"><nav class=\"px-8 py-6 flex items-center space-x-12\"><div class=\"text-4xl font-serif\">Lenslocked</div><div><a class=\"text-lg font-semibold hover:text-blue-100 pr-8\" href=\"/\">Home</a> <a class=\"text-lg font-semibold hover:text-blue-100 pr-8\" href=\"/contact\">Contact</a> <a class=\"text-lg font-semibold hover:text-blue-100 pr-8\" href=\"/faq\">FAQ</a></div><div class=\"flex-grow\"></div><div class=\"space-x-4\"><a href=\"/signin\" class=\"pr-4\">Sign in</a> <a href=\"/signup\" class=\"px-4 py-2 bg-blue-700 hover:bg-blue-600 rounded\">Sign up</a></div></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
