// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordReset struct {
	ID        int32
	UserID    pgtype.Int4
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	IsAdmin      bool
}
